Repository Vanshika2063/Leetcode-Questions, pull requests merged in 2022-10, with the labels that each got.

#12 Create Search_in_rotated_SortedArray.cpp
  Medium/Search_in_rotated_SortedArray.cpp
Labels: question, hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#11 Create Merge_k_sorted_list.cpp
  Hard/Merge_k_sorted_list.cpp
Labels: question, hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#10 Create Swap Nodes In Pairs
  Medium/Swap Nodes In Pairs
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#6 Remove Duplicates from Sorted Array
  Medium/Remove Duplicates from Sorted Array/solution.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#5 Maximum Subarray
  Easy/MergeArray.java
  Medium/KadaneAlgo.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#4 Added a C++ Program
  Easy/longestCommanPrefix.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#3 Best Time To Buy And Sell Stock
  Easy/Best_Time_to_Buy_and_Sell_Stock.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#13 Create subsets.CPP
  Medium/subsets.CPP
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#14 "added find middle of the linked list"
  Easy/MiddleNodeLinkedList.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#17 Added Two Questions, Easy and Medium
  Easy/2315. Count Asterisks.cpp
  Medium/Find Peak Element.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#15 Added solution for LC problem : 443. String Compression
  Medium/stringCompression.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#18 add ts and js
  Easy/PalindromeNumber.ts
  Easy/ShuffleTheArray.js
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#19 "added two medium level questions #16"
  Medium/AddTwoNumbersLinkedList.java
  Medium/DeleteNodeLinkedList.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#20 Factorial.java
  Easy/Factorial.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#21 Added a C++ Hard Program
  Hard/largest_Rectangle_in_Histogram.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#22 Inheritance.java
  Easy/Inheritance.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#23 BubbleSort.java
  Hard/BubbleSort.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#24 LargestnumberofArray.java
  Medium/LargestnumberofArray.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#25 Prime Number
  primeNumber
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#26 PrimeNumber.java
  Easy/PrimeNumber.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#27 add python solutions
  Easy/29-Can-make-arithmetic-progression-from-sequence.py
  Easy/BestTimeToBuyStock.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#28 EvenOddNumber.java
  Easy/EvenOddNumber.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#29 Armstrongnumber.java
  Medium/Armstrongnumber.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#33 added solution for 4sum in cpp
  Medium/4sum.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#32 "added two questions fixes #31"
  Medium/LinkedListCycleII.java
  Medium/SetMatrixZero.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#34 Median of Two Sorted Arrays added in hard
  Hard/Median_of_ Two_Sorted_Arrays.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#35 added ValidSudoko.cpp
  Medium/ValidSudoko.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#36 added an easy and a medium solution
  Easy/ArrangingCoins.java
  Hard/MedianOfTwoSortedArrays.java
  Medium/RotatedBSDuplicates.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#37 50. Pow(x, n)
  Medium/powXN.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#38 169. Majority Element
  Easy/MajorityElement.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#42 Roman to integer || LeetCode || 13
  Easy/Roman to integer.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#43 67. Add Binary
  Easy/Add_Binary.cpp
Labels: hacktoberfest2022, hacktoberfest

#44 Create TopoLogical-Sort.cpp
  Hard/TopoLogical-Sort.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#55 solved 4sum in cpp
  Medium/4sum.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#54 2425 Bitwise XOR of All Pairings: cpp solution added
  Medium/2425. Bitwise XOR of All Pairings.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#53 Added longest common prefix
  Easy/LongestPrefix.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#52 Added Problem No. 976 of LeetCode
  Easy/976. Largest Perimeter Triangle.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#51 Added "DecodeWays" Medium Answer in CPP
  Medium/DecodeWays.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#50 added skyline.java
  Hard/skyline.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#49 added program 9,13,20,14 all in cpp format
  Easy/13Roman_to_Integer.cpp
  Easy/14LongestCommonPrefix.cpp
  Easy/20Valid_ParenthesesLC.cpp
  Easy/9._Palindrome Number(LC).cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#48 added Subarray Sum Equals K solution
  Medium/Subarray Sum Equals K.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#56 #39 - Add java solution of 91. Decode Ways
  Medium/91/ Decode Way/Solution.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#46 Added Question count_items_matching_a_rule in Easy Folder
  Easy/count_items_matching_a_rule.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#58 add fizzbuzz
  Easy/FizzBuzz.js
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#57 numRollsToTarget
  Medium/numRollsToTarget.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#59 217. Contains duplicate
  Easy/217. Contains Duplicate
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#60 121. Best Time to Buy and Sell Stock
  121. Best Time to Buy and Sell Stock
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#61 2428 Maximum Sum of an Hour Glass : cpp solution added
  Medium/2428. Maximum Sum of an Hourglass.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#62 A_Restoring Numbers
  Easy/A_Restoring_numbers
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#63 Quick Sort Program in C++ using Recursion
  Easy/quick_sort.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#66 linkedlist.c
  linkedlist.c
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#67 78. Subsets
  Medium/78. Subsets
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#68 Added DecodeWays
  Medium/DecodeWays.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#69 Fraction_Class.cpp
  Hard/Fraction_class.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#70 Create Number_of_Pairs_Satisfying_Inequality.cpp
  Hard/Number_of_Pairs_Satisfying_Inequality.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#71 Added solution for Build Array From Permutation
  Easy/Build-Array-From-Permutation
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#72 Added solution for 2 sum
  Easy/twoSum.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#73 Fair_play.cpp
  Medium/Fair_play.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#74 a_sum_of_round_numbers
  Easy/A_SUM_OF_Round_Numbers
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#81 Intuition added
  Easy/Best_Time_to_Buy_and_Sell_Stock.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#78 Create 139-word-break.cpp
  Medium/139-word-break.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#75 good_pair.cpp
  Medium/good_pair.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#76 Create Ransom Note.cpp
  Easy/Ransom Note.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#77 #40 - Add python solution of 91. Decode Ways
  Medium/91/ Decode Way/Solution.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#83 Create 11.Containerwithmostwater.java
  Medium/11.Containerwithmostwater.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#82 Weekly Contest 313
  Hard/Maximum Deletions on a String.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#85 add leetcode ques
  Easy/2367. Number of Arithmetic Triplets.cpp
  Hard/336. Palindrome Pairs.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#84 Dsa solutions
  Medium/Lru-cache.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#90 Solution for Problem.58
  Easy/Length_of_last_word.cpp
  Easy/Problem_69.Sqrt(x).cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#92 Create ArrangingCoins441.java
  Easy/ArrangingCoins441.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#93 Add files via upload
  main (3).cpp
  main (4).cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#94 solution to Reverse Integer problem on leetcode
  Medium/Problem7.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#95 427_A.cpp
  Easy/427_A.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#97 Create AddContainerwithMostWater.java
  Medium/AddContainerwithMostWater.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#107 Longsharing_chef.cpp
  Easy/Long_sharing_chef.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#106 leetcode easy problem
  Easy/876. Middle of the Linked List.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#105 Add new files to easy and medium folder. Deleted duplicate files in same language.
  Easy/Move Zeroes/Move Zeroes.py
  Easy/plus one.py
  Medium/AddContainerwithMostWater.java
  Medium/Container With Most Water/Container With Most Water.java
  Medium/Container With Most Water/Container With Most Water.py
  Medium/Fruit Into Baskets.py
  README.md
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#104 Longest substring
  Medium/Longest Substring Without Repeating Characters.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#103 added Maximum Product of Three Numbers solution
  Easy/Maximum Product of Three Numbers.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#102 #79 - Add java solution for 1155. Number of Dice Rolls With Target Sum
  Medium/1155/ Number of Dice Rolls With Target Sum/Solution.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#101 trapping rain water code added
  Hard/trapping_rain_water.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#100 explained with intuition
  Hard/25.Reverse_Nodes_in_K_Groups.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#122 Remove duplicate
  Easy/Remove Duplicates from Sorted Array.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#124 Add files via upload
  Medium/240. Search a 2D Matrix II/Search2DMatrix.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#121 Create Sum_of_two_integers.cpp
  Medium/Sum_of_two_integers.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#120 Create lineartree.cpp
  Hard/lineartree.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#119 Create Maximal-square.cpp
  Medium/Maximal-square.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#118 added medium leetcode
  Medium/695. Max Area of Island.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#108 Update main (3).cpp
  main (3).cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#116 #80 - Add python solution for 1155. Number of Dice Rolls With Target Sum
  Medium/1155/ Number of Dice Rolls With Target Sum/Solution.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#114 99-Recovery binary search tree LeetCode
  Medium/99-Recovery-Binary-searchTree
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#112 Create 101. Symmetric Tree
  Easy/101. Symmetric Tree
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#111 Create MaximumElementAfterDecreasingAndRearranging.cpp
  Easy/MaximumElementAfterDecreasingAndRearranging.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#110 Create 8.String_to_integer(atoi).cpp
  Medium/8.String_to_integer(atoi).cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#126 Create AggressiveCows.cpp
  Hard/AggressiveCows.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#129 Solved issue #128 Add Minimum_Absolute_Sum_Difference to the repo
  Medium/Minimum_Absolute_Sum_Difference.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#151 added some medium questions
  Medium/KClosestElement.java
  Medium/KoKoEatingBanana.java
  Medium/MaxSubArraySum.java
  Medium/ShipCapacity.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#152 added some more questions
  Easy/CountNegGrid.java
  Easy/SmallestLetter.java
  Easy/Sqrt.java
  Easy/kthSmallestInMatrix.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#132 removes duplicates from easy
  Easy/121. Best Time to Buy and Sell Stock
  Easy/14LongestCommonPrefix.cpp
  Easy/ArrangingCoins.java
  Easy/PrimeNumber.java
  Easy/Roman to integer.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#134 added-word-ladder
  Hard/Word Ladder.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#138 Added the code on Removing Nth Node from End of Linked List
  Medium/RemoveNthNodeFromEnd.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#139 ADDED SOLUTION FOR LC PROBLEM : 114. Flatten Binary Tree to Linked List
  Medium/flattenBTtoLL.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#140 Create 852.Peak Index in a Mountain Array
  Medium/852.Peakindex.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#143 Create NumsNotInArrayLeetcode448.java
  Easy/NumsNotInArrayLeetcode448.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#144 NextPermutation and SetMatrixZeroes
  Medium/nextPermutation.cpp
  Medium/setMatrixZeroes.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#148 added zigzag_traversal_binary_tree
  Medium/zigzag_traversal_binary_tree.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#145 Create DisBetweenTwoArrayLeetcode1385.java
  Easy/DisBetweenTwoArrayLeetcode1385.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#158 Subset Sum Problem
  Hard/Subset_Sum_Problem.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#157 Added Leetcode(34)
  Medium/34.First_And_Last_Occurence_of_an_Element.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#159 intersection of two arrays
  Medium/IntersectionOfTwoArrays.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#160 add some LC M $ E sol
  Easy/2399_check_distance_between_same_letters.java
  Medium/240. Search a 2D Matrix II/48 Rotate Image/rotate_image_48.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#161 Weekly Contest 302
  Hard/Array_Divisible.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#193 Create closestKvalues.java
  Hard/closestKvalues.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#195 Biweekly Contest 80
  Hard/Count Subarrays.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#194 Create numberToWords.java
  Hard/numberToWords.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#192 Create findMin.java
  Hard/findMin.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#191 Create ladderLength.java
  Hard/ladderLength.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#190 Create trap1.java
  Hard/trap1.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#187 Added First Missing Positive Leetcode Hard Problem
  Hard/first_missing_positive.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#185 Spiral Matrix
  Medium/Spiral_Matrix.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#183 Leetcode (62) added
  Medium/62.Unique_paths.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#182 Minimum Time to make Rope Colourful
  Medium/Minimum time to make Rope Colourful.cpp
  Medium/Pseudo-Palindromic Paths in a Binary Tree.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#181 Added Triangle.java
  Medium/Triangle.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#164 Added solution for Longest Consecutive Sequence
  Medium/Longest-Consecutive-sequence.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#167 created 3sum.cpp
  Medium/3sum.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#168 Renamed easy questions
  Contains Duplicate
  Easy/A.cpp
  Easy/Can-make-arithmetic-progression-from-sequence.py
  Easy/Count Asterisks.cpp
  Easy/Largest Perimeter Triangle.cpp
  Easy/Middle of the Linked List.py
  Easy/Number of Arithmetic Triplets.cpp
  Easy/Symmetric Tree
  Easy/Valid_ParenthesesLC.cpp
  Easy/check_distance_between_same_letters.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#171 Create Create Maximum sum subarray of size k.cpp
  Easy/Create Maximum sum subarray of size k.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#173 Added Letter_Combinations_of_a_Phone_Number.java
  Medium/Letter_Combinations_of_a_Phone_Number.java
Labels: help wanted, hacktoberfest2022, hactoberfest-accepted

#174 Create min_in_sorted_rotated_sorted_array.py
  Medium/min_in_sorted_rotated_sorted_array.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#175 Added Divide_Two_Integers.cpp
  Medium/Divide_Two_Integers.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#176 Added Combination_Sum.java
  Medium/Combination_Sum.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#177 Added Multiply_Strings.java
  Medium/Multiply_Strings.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#178 Added Jump_Game.java
  Medium/Jump_Game.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#179 Added Unique_Paths.java
  Medium/Unique_Paths.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#196 Add files via upload
  Hard/Substring_with_catenation_of_All_words.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#197 Create Minimum Weighted Subgraph With the Required Paths
  Hard/Minimum Weighted Subgraph With the Required Paths
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#199 added frog positions after t seconds
  Hard/Frog_Position_After_T_Seconds.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#201 Weekly Contest 313
  Medium/Minimize XOR.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#198 LeetCode Hard: N-Queens
  Hard/N-Queens.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#203 Added Two Sum
  Easy/Two_sum.cpp
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#200 added spiral_matrix in java
  Medium/Spiral_Matrix.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#162 Added C++ and Java Solution for leet code 82&2164
  Medium/Count Number  Bad Pairs/leet_code2364.cpp
  Medium/Count Number  Bad Pairs/leetcode23.java
  Medium/Remove Duplicates from sorted linked list (82)/leetcode82.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#202 Create MaximumDepthOfBinaryTree.java
  Easy/MaximumDepthOfBinaryTree.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#204 Added Leetcode Easy Questions
  Easy/Merge_Strings_Alternately1768.java
  Easy/Roman_to_Integer13.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#205 added House robber (Lc medium)
  Medium/House_robber.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#206 Added Linked List Cycle in Python
  Easy/LinkedList_Cycle.py
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#207 added program for plusOne
  Easy/plusOne.js
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#208 3Sume Closest Solution
  Medium/3Sum_Closest.java
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#209 Longest Substring Without Repeating Characters(JavaScript)
  Medium/Longest Substring Without Repeating Characters/solution.js
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted

#211 Recursive c++ code
  Medium/Subsets II/M#1(Recursion CPP)
Labels: hacktoberfest2022, hacktoberfest, hactoberfest-accepted
